### ISSUE TITLE
minor typo

### ISSUE THREAD

**Issue by cmcapellan** [DaveBackus/Amazon_Global_Economy#13]
on page 139: 

"The dot at k = +10 suggests that the correlation of industrial production growth with equity
price growth tex months later is about –0.2."

tex months should be ten months

**Comment by DaveBackus** [comment]
Got it, thanks a lot.  New version due out in Sept, will have the
correction.

**Comment by cmcapellan** [comment]
One more minor typo, I see a few references throughout the text for Kahn
Academy, it's Khan Academy (the founder is Indian, not Jewish!)

Is it obvious I'm studying for a Global Economy final tomorrow? :-)

**Comment by cmcapellan** [comment]
One more:

p. 256 -- Many countries have fixed exchange-rate regimes of one sort or
other. Colombia
uses US dollars, so its currency is fixed by design.

I believe you meant to say Ecuador instead of Colombia here?

**Comment by DaveBackus** [comment]
Done, thanks.
